### ISSUE TITLE
using spacy to train ner merge nertagged data, error

### ISSUE THREAD

**Issue by YanLiang1102** [oudalab/Arabic-NER#12]
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yan/spacyou/spaCy/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/yan/.local/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/yan/.local/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/yan/spacyou/spaCy/spacy/cli/train.py", line 118, in train
    optimizer = nlp.begin_training(lambda: corpus.train_tuples, device=use_gpu)
  File "/home/yan/spacyou/spaCy/spacy/language.py", line 479, in begin_training
    **cfg)
  File "nn_parser.pyx", line 834, in spacy.syntax.nn_parser.Parser.begin_training
  File "ner.pyx", line 88, in spacy.syntax.ner.BiluoPushDown.get_actions
ValueError: need more than 1 value to unpack

**Comment by YanLiang1102** [comment]
'U-MISC': SHOULD not be simpliefied as MISC or we need to change the source code of spacy here:
 if ner_tag != 'O' and ner_tag != '-':
                        _, label = ner_tag.split('-', 1)
in spacy/syntax/ner.pyx 88 change into:
 if ner_tag != 'O' and ner_tag!='MISC' and ner_tag != '-':
                        _, label = ner_tag.split('-', 1)

**Comment by YanLiang1102** [comment]
ok, previous I was thinking either change the tag or change the spacy source code ,
but when change spacy source code, 
Itn.	P.Loss	N.Loss	UAS	NER P.	NER R.	NER F.	Tag %	Token %
train docs length  402
Saving model...                                                                    
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yan/spacyou/spaCy/spacy/__main__.py", line 31, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/yan/eventData/yan-virtualenv/document_cluster/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/home/yan/eventData/yan-virtualenv/document_cluster/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/yan/spacyou/spaCy/spacy/cli/train.py", line 137, in train
    drop=next(dropout_rates), losses=losses)
  File "/home/yan/spacyou/spaCy/spacy/language.py", line 427, in update
    proc.update(docs, golds, drop=drop, sgd=get_grads, losses=losses)
  File "nn_parser.pyx", line 564, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 681, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "ner.pyx", line 118, in spacy.syntax.ner.BiluoPushDown.preprocess_gold
  File "ner.pyx", line 170, in spacy.syntax.ne
this error still happen. so 
B-DATE -> B-MISC
I-DATE->I-MISC
L-DATE->L-MISC....

**Comment by ahalterman** [comment]
Hmm, yeah, I agree that DATE should also go to MISC. Do you know what it was producing that error though?

**Comment by YanLiang1102** [comment]
yeah, I fixed it already, so B-DATE need to be changed to B-MISC instead of MISC.
same as others BILOU will only accept 'O','-' and all other tags needs to start with 'B,I,L'
